// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TT_IDENT-0]
	_ = x[TT_BYTE-1]
	_ = x[TT_STRING-2]
	_ = x[TT_INT-3]
	_ = x[TT_FLOAT-4]
	_ = x[TT_PLUS-5]
	_ = x[TT_MINUS-6]
	_ = x[TT_STAR-7]
	_ = x[TT_SLASH-8]
	_ = x[TT_PERCENT-9]
	_ = x[TT_BIT_AND-10]
	_ = x[TT_BIT_OR-11]
	_ = x[TT_BIT_NOT-12]
	_ = x[TT_BIT_LSH-13]
	_ = x[TT_BIT_RSH-14]
	_ = x[TT_AND-15]
	_ = x[TT_OR-16]
	_ = x[TT_LT-17]
	_ = x[TT_GT-18]
	_ = x[TT_LTE-19]
	_ = x[TT_GTE-20]
	_ = x[TT_EQ-21]
	_ = x[TT_NEQ-22]
	_ = x[TT_QMARK-23]
	_ = x[TT_EMARK-24]
	_ = x[TT_DOT-25]
	_ = x[TT_COLON-26]
	_ = x[TT_COMMA-27]
	_ = x[TT_RANGE-28]
	_ = x[TT_HASH-29]
	_ = x[TT_IS-30]
	_ = x[TT_LBRACK-31]
	_ = x[TT_RBRACK-32]
	_ = x[TT_LBRACE-33]
	_ = x[TT_RBRACE-34]
	_ = x[TT_LPAREN-35]
	_ = x[TT_RPAREN-36]
	_ = x[TT_KW_IF-37]
	_ = x[TT_KW_ELSE-38]
	_ = x[TT_KW_FOR-39]
	_ = x[TT_KW_FUN-40]
	_ = x[TT_KW_BREAK-41]
	_ = x[TT_KW_CONTINUE-42]
	_ = x[TT_KW_RETURN-43]
	_ = x[TT_KW_YIELD-44]
	_ = x[TT_KW_IMPORT-45]
	_ = x[TT_KW_CLASS-46]
	_ = x[TT_KW_MACHINE-47]
	_ = x[TT_KW_ASSERT-48]
	_ = x[TT_KW_IN-49]
	_ = x[TT_CMT_LINE-50]
	_ = x[TT_CMT_DOC-51]
	_ = x[TT_SPECIAL-52]
	_ = x[TT_INVALID-53]
	_ = x[TT_EOF-54]
}

const _TokenType_name = "TT_IDENTTT_BYTETT_STRINGTT_INTTT_FLOATTT_PLUSTT_MINUSTT_STARTT_SLASHTT_PERCENTTT_BIT_ANDTT_BIT_ORTT_BIT_NOTTT_BIT_LSHTT_BIT_RSHTT_ANDTT_ORTT_LTTT_GTTT_LTETT_GTETT_EQTT_NEQTT_QMARKTT_EMARKTT_DOTTT_COLONTT_COMMATT_RANGETT_HASHTT_ISTT_LBRACKTT_RBRACKTT_LBRACETT_RBRACETT_LPARENTT_RPARENTT_KW_IFTT_KW_ELSETT_KW_FORTT_KW_FUNTT_KW_BREAKTT_KW_CONTINUETT_KW_RETURNTT_KW_YIELDTT_KW_IMPORTTT_KW_CLASSTT_KW_MACHINETT_KW_ASSERTTT_KW_INTT_CMT_LINETT_CMT_DOCTT_SPECIALTT_INVALIDTT_EOF"

var _TokenType_index = [...]uint16{0, 8, 15, 24, 30, 38, 45, 53, 60, 68, 78, 88, 97, 107, 117, 127, 133, 138, 143, 148, 154, 160, 165, 171, 179, 187, 193, 201, 209, 217, 224, 229, 238, 247, 256, 265, 274, 283, 291, 301, 310, 319, 330, 344, 356, 367, 379, 390, 403, 415, 423, 434, 444, 454, 464, 470}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
