// Code generated by "stringer -type=tt"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TT_IDENT-0]
	_ = x[TT_STRING-1]
	_ = x[TT_INT-2]
	_ = x[TT_FLOAT-3]
	_ = x[TT_PLUS-4]
	_ = x[TT_MINUS-5]
	_ = x[TT_STAR-6]
	_ = x[TT_SLASH-7]
	_ = x[TT_PERCENT-8]
	_ = x[TT_BIT_AND-9]
	_ = x[TT_BIT_OR-10]
	_ = x[TT_BIT_NOT-11]
	_ = x[TT_BIT_LSH-12]
	_ = x[TT_BIT_RSH-13]
	_ = x[TT_AND-14]
	_ = x[TT_OR-15]
	_ = x[TT_LT-16]
	_ = x[TT_GT-17]
	_ = x[TT_LTE-18]
	_ = x[TT_GTE-19]
	_ = x[TT_EQ-20]
	_ = x[TT_NEQ-21]
	_ = x[TT_QMARK-22]
	_ = x[TT_EMARK-23]
	_ = x[TT_DOT-24]
	_ = x[TT_COLON-25]
	_ = x[TT_COMMA-26]
	_ = x[TT_RANGE-27]
	_ = x[TT_HASH-28]
	_ = x[TT_IS-29]
	_ = x[TT_LBRACK-30]
	_ = x[TT_RBRACK-31]
	_ = x[TT_LBRACE-32]
	_ = x[TT_RBRACE-33]
	_ = x[TT_LPAREN-34]
	_ = x[TT_RPAREN-35]
	_ = x[TT_KW_IF-36]
	_ = x[TT_KW_ELSE-37]
	_ = x[TT_KW_FOR-38]
	_ = x[TT_KW_FUN-39]
	_ = x[TT_KW_BREAK-40]
	_ = x[TT_KW_CONTINUE-41]
	_ = x[TT_KW_RETURN-42]
	_ = x[TT_KW_YIELD-43]
	_ = x[TT_KW_IMPORT-44]
	_ = x[TT_KW_CLASS-45]
	_ = x[TT_KW_MACHINE-46]
	_ = x[TT_KW_ASSERT-47]
	_ = x[TT_KW_IN-48]
	_ = x[TT_CMT_LINE-49]
	_ = x[TT_CMT_DOC-50]
	_ = x[TT_SPECIAL-51]
	_ = x[TT_INVALID-52]
}

const _TokenType_name = "TT_IDENTTT_STRINGTT_INTTT_FLOATTT_PLUSTT_MINUSTT_STARTT_SLASHTT_PERCENTTT_BIT_ANDTT_BIT_ORTT_BIT_NOTTT_BIT_LSHTT_BIT_RSHTT_ANDTT_ORTT_LTTT_GTTT_LTETT_GTETT_EQTT_NEQTT_QMARKTT_EMARKTT_DOTTT_COLONTT_COMMATT_RANGETT_HASHTT_ISTT_LBRACKTT_RBRACKTT_LBRACETT_RBRACETT_LPARENTT_RPARENTT_KW_IFTT_KW_ELSETT_KW_FORTT_KW_FUNTT_KW_BREAKTT_KW_CONTINUETT_KW_RETURNTT_KW_YIELDTT_KW_IMPORTTT_KW_CLASSTT_KW_MACHINETT_KW_ASSERTTT_KW_INTT_CMT_LINETT_CMT_DOCTT_SPECIALTT_INVALID"

var _TokenType_index = [...]uint16{0, 8, 17, 23, 31, 38, 46, 53, 61, 71, 81, 90, 100, 110, 120, 126, 131, 136, 141, 147, 153, 158, 164, 172, 180, 186, 194, 202, 210, 217, 222, 231, 240, 249, 258, 267, 276, 284, 294, 303, 312, 323, 337, 349, 360, 372, 383, 396, 408, 416, 427, 437, 447, 457}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "tt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
